// Code generated by "stringer -type=ClientType"; DO NOT EDIT.

package auth

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Public-1]
	_ = x[Confidential-2]
}

const _ClientType_name = "PublicConfidential"

var _ClientType_index = [...]uint8{0, 6, 18}

func (i ClientType) String() string {
	i -= 1
	if i < 0 || i >= ClientType(len(_ClientType_index)-1) {
		return "ClientType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ClientType_name[_ClientType_index[i]:_ClientType_index[i+1]]
}
